// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervationVB.Models;

namespace RezervationVB.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211012084335_relationmasa")]
    partial class relationmasa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RezervationVB.Models.masa", b =>
                {
                    b.Property<int>("masaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("masadurum")
                        .HasColumnType("bit");

                    b.Property<string>("masaetiketi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("masaid");

                    b.ToTable("TableMasa");
                });

            modelBuilder.Entity("RezervationVB.Models.rezerve", b =>
                {
                    b.Property<int>("rezerveid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kullaniciadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("masaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("rezervebaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("rezervebitis")
                        .HasColumnType("datetime2");

                    b.Property<string>("sicilno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rezerveid");

                    b.HasIndex("masaid")
                        .IsUnique();

                    b.ToTable("TableRezerve");
                });

            modelBuilder.Entity("RezervationVB.Models.rezerve", b =>
                {
                    b.HasOne("RezervationVB.Models.masa", "masa")
                        .WithOne("rezerve")
                        .HasForeignKey("RezervationVB.Models.rezerve", "masaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("masa");
                });

            modelBuilder.Entity("RezervationVB.Models.masa", b =>
                {
                    b.Navigation("rezerve");
                });
#pragma warning restore 612, 618
        }
    }
}
